version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Eq11223344
      MYSQL_DATABASE: resumable
      MYSQL_USER: root
      MYSQL_PASSWORD: Eq11223344
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-pEq11223344',
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  my-app:
    build: .
    container_name: my-app
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: 'mysql://root:Eq11223344@mysql:3306/resumable'
    command: sh -c "npx wait-port mysql:3306 && npx prisma migrate dev && npm run start:dev"
    volumes:
      - .:/app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  mysql-data:
  minio-data:
